FROM langgenius/dify-api:1.5.1
FROM langgenius/dify-api:1.5.1
FROM langgenius/dify-web:1.5.1
FROM postgres:15-alpine
FROM redis:6-alpine
FROM langgenius/dify-sandbox:0.2.12
FROM langgenius/dify-plugin-daemon:0.1.2-local
FROM ubuntu/squid:latest
FROM certbot/certbot
FROM nginx:latest
FROM semitechnologies/weaviate:1.19.0
FROM langgenius/qdrant:v1.7.3
FROM pgvector/pgvector:pg16
FROM vastdata/vastbase-vector
FROM tensorchord/pgvecto-rs:pg16-v0.3.0
FROM ghcr.io/chroma-core/chroma:0.5.20
FROM oceanbase/oceanbase-ce:4.3.5-lts
FROM container-registry.oracle.com/database/free:latest
FROM quay.io/coreos/etcd:v3.5.5
FROM minio/minio:RELEASE.2023-03-20T20-16-18Z
FROM milvusdb/milvus:v2.5.0-beta
FROM opensearchproject/opensearch:latest
FROM opensearchproject/opensearch-dashboards:latest
FROM opengauss/opengauss:7.0.0-RC1
FROM myscale/myscaledb:1.6.4
FROM matrixorigin/matrixone:2.1.1
FROM docker.elastic.co/elasticsearch/elasticsearch:8.14.3
FROM docker.elastic.co/kibana/kibana:8.14.3
FROM downloads.unstructured.io/unstructured-io/unstructured-api:latest
